Repository Yukhoebibimbap/huemap, pull requests merged in 2022-11, with the labels that each got.

#72 [#66] 잘못된 폐쇄 제보 엔티티 & delete 필드 추가에 따른 bin 엔티티 수정
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/report/domain/Closure.java
  backend/src/main/java/com/huemap/backend/report/domain/Report.java
  backend/src/main/java/com/huemap/backend/user/domain/User.java
Labels: 백엔드, 기능

#74 [BE] BinDetailResponse 생성
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinMapper.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
Labels: 백엔드, 기능

#75 [BE] 폐수거함 상세 조회 Controller 구현
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/presentation/BinController.java
Labels: 백엔드, 기능

#80 [#67] 폐쇄 폐수거함 제보 Controller 구현 (잘못된 폐수거함 제보)
  backend/src/main/java/com/huemap/backend/common/validator/LatitudeValid.java
  backend/src/main/java/com/huemap/backend/common/validator/LatitudeValidator.java
  backend/src/main/java/com/huemap/backend/common/validator/LongitudeValid.java
  backend/src/main/java/com/huemap/backend/common/validator/LongitudeValidator.java
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/domain/mapper/ClosureMapper.java
  backend/src/main/java/com/huemap/backend/report/dto/request/ClosureCreateRequest.java
  backend/src/main/java/com/huemap/backend/report/dto/response/ClosureCreateResponse.java
  backend/src/main/java/com/huemap/backend/report/presentation/ReportController.java
  backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
Labels: 백엔드, 테스트, 기능

#77 [BE] 폐수거함 상세 조회 Service 구현
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
  backend/src/main/java/com/huemap/backend/common/exception/BusinessException.java
  backend/src/main/java/com/huemap/backend/common/exception/EntityNotFoundException.java
  backend/src/main/java/com/huemap/backend/common/presentation/ControllerAdvice.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
Labels: 백엔드, 기능

#82 [BE] 좌표 데이터 Point로 변경
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinMapper.java
Labels: 백엔드, 리팩터링

#83 [#65] refactor: MVVM구조 구성
  frontend/lib/bin.dart
  frontend/lib/data/datasource/local_datasource.dart
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/bin.dart
  frontend/lib/data/repository/bin_repository.dart
  frontend/lib/map-page.dart
  frontend/lib/ui/page/map_page.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 프론트엔드, 리팩터링

#85 [#68] 폐쇄 폐수거함 제보 service, repository 구현 & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/common/exception/InvalidValueException.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/common/utils/GeometryUtil.java
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/domain/Closure.java
  backend/src/main/java/com/huemap/backend/report/domain/Report.java
  backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
  backend/src/main/java/com/huemap/backend/report/domain/mapper/ClosureMapper.java
  backend/src/test/java/com/huemap/backend/common/TestUtils.java
  backend/src/test/java/com/huemap/backend/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/report/domain/ReportRepositoryTest.java
  backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 테스트, 기능

#88 [BE] 폐수거함 상세 조회시 잘못된 폐수거함 제보 횟수를 response에 추가
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
  backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
Labels: 백엔드, 기능

#89 [#86] 일정 수 이상 폐쇄 제보 받은 폐수거함 제거 스케줄러 구현
  backend/src/main/java/com/huemap/backend/BackendApplication.java
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinRepository.java
  backend/src/main/java/com/huemap/backend/common/config/SchedulerConfig.java
  backend/src/main/java/com/huemap/backend/common/scheduler/SchedulerService.java
  backend/src/test/java/com/huemap/backend/bin/domain/BinRepositoryTest.java
  backend/src/test/java/com/huemap/backend/common/TestUtils.java
  backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceTest.java
Labels: 백엔드, 테스트, 기능

#94 [#90] 존재 폐수거함 제보 엔티티 정의
  backend/src/main/java/com/huemap/backend/report/domain/Presence.java
Labels: 백엔드, 기능

#95 [#91] 존재 폐수거함 제보 controller 구현 & 테스트 구현
  backend/src/main/java/com/huemap/backend/bin/domain/BinType.java
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/dto/request/PresenceCreateRequest.java
  backend/src/main/java/com/huemap/backend/report/dto/response/PresenceCreateResponse.java
  backend/src/main/java/com/huemap/backend/report/presentation/ReportController.java
  backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
Labels: 백엔드, 테스트, 기능

#96 [#84] feat: 지도화면 핀 초기화
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/bin.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
Labels: 프론트엔드, 기능

#98 [BE] 폐수거함 설치 건의 엔티티 정의
  backend/src/main/java/com/huemap/backend/suggestion/domain/Suggestion.java
Labels: 백엔드, 기능

#105 [BE] 폐수거함 설치 건의 controller 구현
  backend/src/main/java/com/huemap/backend/suggestion/application/SuggestionService.java
  backend/src/main/java/com/huemap/backend/suggestion/dto/request/SuggestionCreateRequest.java
  backend/src/main/java/com/huemap/backend/suggestion/dto/response/SuggestionCreateResponse.java
  backend/src/main/java/com/huemap/backend/suggestion/presentation/SuggestionController.java
Labels: 백엔드, 기능

#106 [#92] 후보 폐수거함 생성 & 존재 폐수거함 제보 구현
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinRepository.java
  backend/src/main/java/com/huemap/backend/bin/event/BinCreateEvent.java
  backend/src/main/java/com/huemap/backend/bin/event/BinEventHandler.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/common/utils/GeometryUtil.java
  backend/src/main/java/com/huemap/backend/openApi/kakao/KakaoMapEnum.java
  backend/src/main/java/com/huemap/backend/openApi/kakao/KakaoMapProvider.java
  backend/src/main/java/com/huemap/backend/openApi/kakao/response/KakaoMap.java
  backend/src/main/java/com/huemap/backend/openApi/kakao/response/KakaoMapAddress.java
  backend/src/main/java/com/huemap/backend/openApi/kakao/response/KakaoMapRoadAddress.java
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/domain/Presence.java
  backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
  backend/src/main/java/com/huemap/backend/report/domain/mapper/PresenceMapper.java
  backend/src/main/java/com/huemap/backend/report/dto/response/PresenceCreateResponse.java
  backend/src/test/java/com/huemap/backend/common/TestUtils.java
  backend/src/test/java/com/huemap/backend/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/report/domain/ReportRepositoryTest.java
Labels: 백엔드, 기능

#109 [BE] getX gexY 경도 위도로 변경
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinMapper.java
Labels: :bug: 버그, 백엔드

#111 [BE] 폐수거함 설치 건의 service구현
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/suggestion/application/SuggestionService.java
  backend/src/main/java/com/huemap/backend/suggestion/domain/Suggestion.java
  backend/src/main/java/com/huemap/backend/suggestion/domain/SuggestionRepository.java
  backend/src/main/java/com/huemap/backend/suggestion/domain/mapper/SuggestionCreateMapper.java
  backend/src/main/java/com/huemap/backend/suggestion/dto/request/SuggestionCreateRequest.java
  backend/src/main/java/com/huemap/backend/suggestion/dto/response/SuggestionCreateResponse.java
  backend/src/main/java/com/huemap/backend/suggestion/exception/SuggestionLimitExceededException.java
  backend/src/main/java/com/huemap/backend/suggestion/presentation/SuggestionController.java
Labels: 백엔드, 기능

#113 [#93] 후보 폐수거함 승급 스케줄러 구현
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinRepository.java
  backend/src/main/java/com/huemap/backend/common/scheduler/SchedulerService.java
  backend/src/main/java/com/huemap/backend/report/domain/Closure.java
  backend/src/main/java/com/huemap/backend/report/domain/Presence.java
  backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
  backend/src/test/java/com/huemap/backend/bin/domain/BinRepositoryTest.java
  backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceIntegrationTest.java
  backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceTest.java
Labels: 백엔드, 테스트, 기능

#117 [#115] 후보 폐수거함 투표 controller 구현 & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/dto/request/PresenceVoteRequest.java
  backend/src/main/java/com/huemap/backend/report/presentation/ReportController.java
  backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
Labels: 백엔드, 테스트, 기능

#118 [BE] 폐수거함 조회시 후보 여부 포함
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
  backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinMapper.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
Labels: 백엔드, 리팩터링, 기능

#120 [#116] 후보 폐수거함 투표 service & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/report/domain/Presence.java
  backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
  backend/src/main/java/com/huemap/backend/report/presentation/ReportController.java
  backend/src/test/java/com/huemap/backend/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
Labels: 백엔드, 테스트, 기능

#126 [#125] 폐수거함 전체 조회 local cache 적용
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/bin/presentation/BinController.java
  backend/src/main/java/com/huemap/backend/common/config/CacheConfig.java
  backend/src/main/java/com/huemap/backend/common/config/CacheType.java
Labels: 백엔드, 리팩터링

#128 [WEB] 공공기관 웹페이지 Vue 초기 설정
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf.d/app.conf
  web/.gitignore
  web/Dockerfile
  web/README.md
  web/babel.config.js
  web/jsconfig.json
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/public/index.html
  web/src/App.vue
  web/src/assets/logo.png
  web/src/assets/logo.svg
  web/src/components/mainBar.vue
  web/src/main.js
  web/src/plugins/vuetify.js
  web/src/router/index.js
  web/src/view/mainPage.vue
  web/src/view/newPage.vue
  web/src/view/subPage.vue
  web/vue.config.js
Labels: 프론트엔드, 기능

#129 [BE] 폐수거함 전체 조회 테스트 코드 작성
  backend/src/test/java/com/huemap/backend/bin/application/BinServiceTest.java
  backend/src/test/java/com/huemap/backend/bin/domain/BinRepositoryTest.java
  backend/src/test/java/com/huemap/backend/bin/presentation/BinControllerTest.java
Labels: 백엔드, 테스트

#131 [BE] 폐수거함 상세 조회 테스트 코드 작성
  backend/src/test/java/com/huemap/backend/bin/application/BinServiceTest.java
  backend/src/test/java/com/huemap/backend/bin/presentation/BinControllerTest.java
Labels: 백엔드, 테스트

#142 [#103] feat: 수거함 표시 토글 버튼 구현
  frontend/lib/data/model/bin.dart
  frontend/lib/data/repository/bin_repository.dart
  frontend/lib/ui/page/map_page.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
Labels: 프론트엔드, 기능

#141 [BE] 폐수거함 설치 건의 조회 Controller 구현
  backend/src/main/java/com/huemap/backend/domain/suggestion/application/SuggestionService.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/dto/response/SuggestionResponse.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
Labels: 백엔드, 기능

#145 [BE] 폐수거함 설치 건의 조회 Service 구현
  backend/src/main/java/com/huemap/backend/domain/suggestion/application/SuggestionService.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/domain/SuggestionRepository.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/domain/mapper/SuggestionMapper.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/dto/response/SuggestionResponse.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
Labels: 백엔드, 기능

#147 [#133] 폐수거함 상태 제보 controller 구현 & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/domain/bin/domain/ConditionType.java
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/domain/report/dto/request/ConditionCreateRequest.java
  backend/src/main/java/com/huemap/backend/domain/report/dto/response/ConditionCreateResponse.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
Labels: 백엔드, 테스트, 기능

#148 [#134] 폐수거함 상태 제보 service 구현 & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/Condition.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/Image.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/mapper/ConditionMapper.java
  backend/src/test/java/com/huemap/backend/common/IntegrationTest.java
  backend/src/test/java/com/huemap/backend/common/TestUtils.java
  backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceIntegrationTest.java
  backend/src/test/java/com/huemap/backend/domain/bin/event/BinEventHandlerIntegrationTest.java
  backend/src/test/java/com/huemap/backend/domain/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/infrastructure/openApi/KakaoMapProviderIntegrationTest.java
  backend/src/test/java/com/huemap/backend/infrastructure/s3/S3UploaderTest.java
Labels: 백엔드, 테스트, 기능

#151 [#150] 유저 엔티티 정의
  backend/src/main/java/com/huemap/backend/domain/user/domain/User.java
Labels: 백엔드, 기능

#154 [#143] feat: 사용자 핀 설치 기능, 제보 건의 버튼 기능 추가
  frontend/lib/data/model/bin.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
Labels: 프론트엔드, 기능

#153 [#152] redis session 추가
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/BackendApplication.java
  backend/src/main/java/com/huemap/backend/common/config/RedisConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceIntegrationTest.java
  backend/src/test/java/com/huemap/backend/domain/bin/application/BinServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/bin/domain/BinRepositoryTest.java
  backend/src/test/java/com/huemap/backend/domain/bin/event/BinEventHandlerIntegrationTest.java
  backend/src/test/java/com/huemap/backend/domain/bin/presentation/BinControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/report/domain/ReportRepositoryTest.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
  backend/src/test/java/com/huemap/backend/infrastructure/openApi/KakaoMapProviderIntegrationTest.java
  backend/src/test/java/com/huemap/backend/infrastructure/s3/S3UploaderTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
  backend/src/test/java/com/huemap/backend/support/IntegrationTest.java
  backend/src/test/java/com/huemap/backend/support/RepositoryTest.java
  backend/src/test/java/com/huemap/backend/support/S3MockConfig.java
  backend/src/test/java/com/huemap/backend/support/TestRedisConfig.java
  backend/src/test/java/com/huemap/backend/support/TestUtils.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 설정

#156 [BE] 도커 환경에서 profile prod 적용 & redis 적용
  backend/Dockerfile
  docker-compose.yml
  web/nginx/nginx.conf
Labels: 백엔드, 인프라, 설정

#161 [#158] User 회원가입 Controller 구현
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/domain/user/application/UserService.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/request/UserCreateRequest.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/response/UserCreateResponse.java
  backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
  backend/src/test/java/com/huemap/backend/domain/user/UserControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
Labels: 백엔드, 기능

#163 [#155] feat: 사용자 페이지 뷰 작성
  frontend/lib/ui/page/map_page.dart
  frontend/lib/ui/page/root_page.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/view/user_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/lib/ui/viewmodel/user_viewmodel.dart
Labels: 프론트엔드, 기능

#162 [BE] 폐수거함 상태 제보시 socket 이벤트 기능 구현
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/Condition.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/mapper/ConditionMapper.java
  backend/src/main/java/com/huemap/backend/domain/report/dto/response/ConditionResponse.java
  backend/src/main/java/com/huemap/backend/infrastructure/socket/SocketModule.java
  backend/src/main/java/com/huemap/backend/infrastructure/socket/SocketService.java
  backend/src/main/java/com/huemap/backend/infrastructure/socket/config/ServerCommandLineRunner.java
  backend/src/main/java/com/huemap/backend/infrastructure/socket/config/SocketIOConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/huemap/backend/domain/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/support/IntegrationTest.java
  backend/src/test/java/com/huemap/backend/support/TestUtils.java
  backend/src/test/resources/application.yml
  web/src/view/chatTest2.vue
Labels: 백엔드, 프론트엔드, 기능

#167 [#165] 로그인 controller 구현 & 단위테스트 구현
  backend/src/main/java/com/huemap/backend/domain/user/application/LoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/application/SessionLoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/request/UserLoginRequest.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/response/UserLoginResponse.java
  backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
  backend/src/test/java/com/huemap/backend/domain/user/presentation/UserControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
Labels: 백엔드, 테스트, 기능

#170 [#166] session login service 구현 & 단위 테스트 구현
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/domain/user/application/SessionLoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/application/UserService.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/User.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/UserMapper.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/UserRepository.java
  backend/src/test/java/com/huemap/backend/domain/user/application/SessionLoginServiceTest.java
  backend/src/test/java/com/huemap/backend/support/TestUtils.java
Labels: 백엔드, 테스트, 기능

#172 [WEB] 폐수거함 상태 소켓 이벤트시 마커 띄우기 구현
  web/src/view/binStatePage.vue
  web/src/view/selectGuPage.vue
Labels: 프론트엔드, 기능

#174 [#168] 사용자 인증 구현
  backend/src/main/java/com/huemap/backend/common/annotation/AuthRequired.java
  backend/src/main/java/com/huemap/backend/common/annotation/CurrentUserId.java
  backend/src/main/java/com/huemap/backend/common/config/WebConfig.java
  backend/src/main/java/com/huemap/backend/common/exception/AuthException.java
  backend/src/main/java/com/huemap/backend/common/resolver/AuthInterceptor.java
  backend/src/main/java/com/huemap/backend/common/resolver/CurrentUserIdResolver.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
  backend/src/main/java/com/huemap/backend/domain/user/application/LoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/application/SessionLoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
  backend/src/test/java/com/huemap/backend/domain/bin/presentation/BinControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
Labels: 백엔드, 테스트, 기능

#177 [#169]: 웹 문서 로컬 이주
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/assets/map.css
  frontend/assets/map.html
  frontend/assets/map.js
  frontend/assets/markers/current.png
  frontend/assets/markers/tile000.png
  frontend/assets/markers/tile001.png
  frontend/assets/markers/tile002.png
  frontend/assets/markers/tile003.png
  frontend/assets/markers/tile004.png
  frontend/assets/markers/tile005.png
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 프론트엔드, 리팩터링

#175 [BE] 폐수거함 상태 조회 Controller 구현
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/domain/report/dto/response/ConditionResponse.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
Labels: 기능

#178 [BE] 폐수거함 설치 건의 테스트 코드 작성
  backend/src/main/java/com/huemap/backend/domain/suggestion/application/SuggestionService.java
  backend/src/test/java/com/huemap/backend/domain/suggestion/application/SuggestionServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/suggestion/domain/SuggestionRepositoryTest.java
  backend/src/test/java/com/huemap/backend/domain/suggestion/presentation/SuggestionControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
  backend/src/test/java/com/huemap/backend/support/RepositoryTest.java
  backend/src/test/java/com/huemap/backend/support/TestUtils.java
Labels: 백엔드, 테스트

#180 [BE] 폐수거함 상태 조회 Service 구현
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/main/java/com/huemap/backend/domain/report/domain/ReportRepository.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
Labels: 백엔드, 기능

#184 [#183] Controller 테스트 mock 메소드 통합
  backend/src/test/java/com/huemap/backend/domain/bin/presentation/BinControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/suggestion/presentation/SuggestionControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/user/presentation/UserControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
Labels: 백엔드, 리팩터링

#186 [#185] 회원가입, 로그인 비즈니스 에러 Controller 테스트
  backend/src/test/java/com/huemap/backend/domain/user/presentation/UserControllerTest.java
Labels: 백엔드, 테스트

#189 [#182] feat: login view 작성
  frontend/lib/ui/page/root_page.dart
  frontend/lib/ui/view/login_view.dart
Labels: 프론트엔드, 기능

#188 [WEB] 폐수거함 상태 조회 마커 띄우기
  web/src/App.vue
  web/src/assets/bin.png
  web/src/assets/css/overlay.css
  web/src/assets/seoul.geojson
  web/src/assets/seoul2.json
  web/src/router/index.js
  web/src/service/kakaoService.js
  web/src/view/binStatePage.vue
  web/src/view/chatTest.vue
  web/src/view/chatTest2.vue
  web/src/view/selectGuPage.vue
Labels: 프론트엔드, 기능

#190 [#187] 제보 도메인 비즈니스 에러 Controller 테스트
  backend/src/main/java/com/huemap/backend/common/config/WebConfig.java
  backend/src/main/java/com/huemap/backend/common/interceptor/AuthInterceptor.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/domain/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/domain/bin/domain/BinRepository.java
  backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
  backend/src/test/java/com/huemap/backend/domain/bin/application/BinServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/report/application/ReportServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
Labels: 백엔드, 테스트

#192 [WEB] 폐수거함 설치 건의 마커 띄우기 구현
  web/src/components/mainBar.vue
  web/src/router/index.js
  web/src/view/binStatePage.vue
  web/src/view/binSuggestionPage.vue
  web/src/view/stateSelectGuPage.vue
  web/src/view/suggestionSelectGuPage.vue
Labels: 프론트엔드, 기능

#194 [DATA] flask 서버 rds 연동
  data/Dockerfile
  data/app.py
  data/route/app_route.py
  data/route/routes.py
Labels: 데이터, 기능, 설정

#198 [DATA] 폐수거함 설치 건의 클러스터링 구현
  data/Dockerfile
  data/app.py
  data/service/kmeansCluster.py
  web/src/view/suggestionSelectGuPage.vue
Labels: 데이터, 기능

#200 [WEB] 클러스터링 결과 마커 띄우기 구현
  data/app.py
  data/service/kmeansCluster.py
  web/src/view/binSuggestionPage.vue
  web/src/view/mainPage.vue
Labels: 프론트엔드, 데이터, 기능

#203 [BE] 도커 nginx 소켓 통신 버그 해결
  backend/src/main/resources/application.yml
  docker-compose.yml
  nginx/conf.d/app.conf
  web/src/view/binStatePage.vue
Labels: :bug: 버그, 백엔드, 프론트엔드, 인프라, 설정

#208 [WEB] 구 선택 레이아웃 수정
  appspec.yml
  web/package-lock.json
  web/package.json
  web/src/assets/css/overlay.css
  web/src/assets/seoul.geojson
  web/src/view/stateSelectGuPage.vue
  web/vue.config.js
Labels: 프론트엔드, 기능

#210 [WEB] 메인페이지 레이아웃 수정
  web/src/components/mainBar.vue
  web/src/router/index.js
  web/src/view/mainPage.vue
  web/src/view/selectGuPage.vue
  web/src/view/suggestionSelectGuPage.vue
Labels: 프론트엔드

#212 [WEB] 폐수거함 상태, 건의 조회 레이아웃 수정
  web/src/view/binStatePage.vue
  web/src/view/binSuggestionPage.vue
  web/src/view/mainPage.vue
  web/src/view/selectGuPage.vue
Labels: 프론트엔드
