Repository Yukhoebibimbap/huemap, pull requests merged in 2022-10, with the labels that each got.

#30 [#29] fix: CI 이벤트 발생 브랜치 수정
  .github/workflows/backend-ci.yml
Labels: :bug: 버그

#33 [#32] AWS RDS 적용
  .github/workflows/backend-ci.yml
  .gitignore
  backend/src/main/java/com/huemap/backend/user/domain/User.java
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 백엔드, 기능, 인프라, 설정

#46 [#37] chore: github action yml ci cd 분리
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
Labels: 백엔드, 인프라, 설정

#48 [#41] Base Entity 생성
  backend/src/main/java/com/huemap/backend/BackendApplication.java
  backend/src/main/java/com/huemap/backend/common/entity/BaseEntity.java
  backend/src/main/java/com/huemap/backend/user/domain/User.java
Labels: 백엔드, 기능

#56 [#53] MapStruct 라이브러리 dependency 추가
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/user/domain/UserMapper.java
Labels: 백엔드, 설정

#55 [#39] Bin Entity 생성
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinType.java
Labels: 백엔드, 기능

#57 [#40] feat: 폐수거함 전체 조회 Controller 구현
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
  backend/src/main/java/com/huemap/backend/bin/presentation/BinController.java
Labels: 백엔드, 기능

#58 [BE] Bin 폐수거함 전체 조회 Service 구현
  backend/src/main/java/com/huemap/backend/bin/application/BinService.java
  backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinMapper.java
  backend/src/main/java/com/huemap/backend/bin/domain/BinRepository.java
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
  backend/src/main/java/com/huemap/backend/bin/presentation/BinController.java
  backend/src/main/java/com/huemap/backend/common/presentation/ControllerAdvice.java
Labels: 백엔드, 기능

#63 [#62] feat: BinResponse에 updatedAt 필드 추가
  backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
Labels: 백엔드, 기능

#64 [#61] API 요청 모듈 작성
  frontend/lib/map-page.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 프론트엔드, 기능
