Repository Yukhoebibimbap/huemap, pull requests merged in 2022-12, with the labels that each got.

#213 [#195] 로그인 구현 및 기타
  frontend/assets/map.js
  frontend/assets/markers/candidate000.png
  frontend/assets/markers/candidate001.png
  frontend/assets/markers/candidate002.png
  frontend/assets/markers/candidate003.png
  frontend/assets/markers/candidate004.png
  frontend/assets/markers/candidate005.png
  frontend/assets/markers/tile004.png
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/bin.dart
  frontend/lib/data/model/signInInfo.dart
  frontend/lib/data/model/signUpInfo.dart
  frontend/lib/data/model/voteInfo.dart
  frontend/lib/data/repository/bin_repository.dart
  frontend/lib/data/repository/signInfo_repository.dart
  frontend/lib/ui/page/login_page.dart
  frontend/lib/ui/page/root_page.dart
  frontend/lib/ui/view/login_view.dart
  frontend/lib/ui/view/signup_view.dart
  frontend/lib/ui/view/vote_view.dart
  frontend/lib/ui/viewmodel/login_viewmodel.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/lib/ui/viewmodel/signup_viewmodel.dart
Labels: 프론트엔드

#215 [#214] 세부 기능 페이지 충돌 해결
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/assets/map.js
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/binDetail.dart
  frontend/lib/data/repository/bin_repository.dart
  frontend/lib/ui/get_camera_image.dart
  frontend/lib/ui/page/login_page.dart
  frontend/lib/ui/page/root_page.dart
  frontend/lib/ui/view/condition_view.dart
  frontend/lib/ui/view/detail_view.dart
  frontend/lib/ui/view/dialog_view.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/view/missing_view.dart
  frontend/lib/ui/view/report_view.dart
  frontend/lib/ui/view/suggestion_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/widget_test.dart
Labels: 프론트엔드, 테스트, 설정

#218 [#217] spring security jwt 로그인 방식 변경
  .github/workflows/backend-cd.yml
  backend/build.gradle
  backend/src/main/java/com/huemap/backend/BackendApplication.java
  backend/src/main/java/com/huemap/backend/common/annotation/AuthRequired.java
  backend/src/main/java/com/huemap/backend/common/annotation/CurrentUserId.java
  backend/src/main/java/com/huemap/backend/common/config/JwtConfig.java
  backend/src/main/java/com/huemap/backend/common/config/RedisConfig.java
  backend/src/main/java/com/huemap/backend/common/config/SecurityConfig.java
  backend/src/main/java/com/huemap/backend/common/config/WebConfig.java
  backend/src/main/java/com/huemap/backend/common/interceptor/AuthInterceptor.java
  backend/src/main/java/com/huemap/backend/common/resolver/CurrentUserIdResolver.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
  backend/src/main/java/com/huemap/backend/common/response/error/ErrorResponse.java
  backend/src/main/java/com/huemap/backend/common/security/AccessDeniedHandlerImpl.java
  backend/src/main/java/com/huemap/backend/common/security/CurrentUser.java
  backend/src/main/java/com/huemap/backend/common/security/CustomAuthenticationEntryPoint.java
  backend/src/main/java/com/huemap/backend/common/security/CustomUserDetailsService.java
  backend/src/main/java/com/huemap/backend/common/security/LoginFailureHandler.java
  backend/src/main/java/com/huemap/backend/common/security/LoginFilter.java
  backend/src/main/java/com/huemap/backend/common/security/LoginSuccessHandler.java
  backend/src/main/java/com/huemap/backend/common/security/TokenAuthenticationFilter.java
  backend/src/main/java/com/huemap/backend/common/security/TokenProvider.java
  backend/src/main/java/com/huemap/backend/common/security/UserPrincipal.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
  backend/src/main/java/com/huemap/backend/domain/user/application/LoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/application/SessionLoginService.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/Role.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/User.java
  backend/src/main/java/com/huemap/backend/domain/user/domain/UserMapper.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/response/AuthResponse.java
  backend/src/main/java/com/huemap/backend/domain/user/dto/response/UserLoginResponse.java
  backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
  backend/src/main/java/com/huemap/backend/infrastructure/socket/config/SocketIOConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/huemap/backend/domain/bin/presentation/BinControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/suggestion/presentation/SuggestionControllerTest.java
  backend/src/test/java/com/huemap/backend/domain/user/application/SessionLoginServiceTest.java
  backend/src/test/java/com/huemap/backend/domain/user/presentation/UserControllerTest.java
  backend/src/test/java/com/huemap/backend/support/ControllerTest.java
  backend/src/test/java/com/huemap/backend/support/WithMockCustomUser.java
  backend/src/test/java/com/huemap/backend/support/WithMockCustomUserSecurityContextFactory.java
Labels: 백엔드, 테스트, 기능

#220 [WEB] 구 선택시 포커스가 해당 구에 맞춰지도록 변경
  web/package-lock.json
  web/package.json
  web/src/assets/seoul2.json
  web/src/main.js
  web/src/store/index.js
  web/src/view/binStatePage.vue
  web/src/view/binSuggestionPage.vue
Labels: 프론트엔드, 기능

#222 [#221] 권한 요청 시 로그인 페이지로 이동
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/userInfo.dart
  frontend/lib/ui/page/login_page.dart
  frontend/lib/ui/page/root_page.dart
  frontend/lib/ui/view/login_view.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/viewmodel/login_viewmodel.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/lib/ui/viewmodel/signup_viewmodel.dart
Labels: 프론트엔드, 기능

#223 [#216] jwt로그인 구현 및 리팩터링 등
  frontend/lib/constant_value.dart
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/model/binDetail.dart
  frontend/lib/data/model/reportPresencesRequest.dart
  frontend/lib/data/model/reportWithUserLocationRequest.dart
  frontend/lib/data/model/suggestBinLocationRequest.dart
  frontend/lib/data/repository/bin_repository.dart
  frontend/lib/data/repository/report_repository.dart
  frontend/lib/data/repository/signInfo_repository.dart
  frontend/lib/data/repository/suggest_repository.dart
  frontend/lib/get_camera_image.dart
  frontend/lib/ui/get_camera_image.dart
  frontend/lib/ui/view/condition_view.dart
  frontend/lib/ui/view/detail_view.dart
  frontend/lib/ui/view/dialog_view.dart
  frontend/lib/ui/view/login_view.dart
  frontend/lib/ui/view/map_view.dart
  frontend/lib/ui/view/missing_view.dart
  frontend/lib/ui/view/report_view.dart
  frontend/lib/ui/view/suggestion_view.dart
  frontend/lib/ui/viewmodel/login_viewmodel.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: :bug: 버그, 프론트엔드, 리팩터링, 기능

#225 [#224] 누락된 로그인창 이동 보완
  frontend/lib/ui/viewmodel/map_viewmodel.dart
Labels: :bug: 버그, 프론트엔드

#227 [BE] 폐수거함 상태 제보 요청 형식 수정
  backend/src/main/java/com/huemap/backend/common/presentation/ControllerAdvice.java
  backend/src/main/java/com/huemap/backend/domain/bin/presentation/BinController.java
  backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
  backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
  backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
  backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
Labels: 백엔드, 기능

#229 [#228] 상태 제보 API 문제 해결
  frontend/lib/constant_value.dart
  frontend/lib/data/datasource/remote_datasource.dart
  frontend/lib/data/repository/report_repository.dart
  frontend/lib/ui/view/condition_view.dart
  frontend/lib/ui/view/dialog_view.dart
  frontend/lib/ui/view/missing_view.dart
  frontend/lib/ui/viewmodel/map_viewmodel.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: :bug: 버그, 프론트엔드, 리팩터링
